#!/usr/bin/env python3
"""Generate the auth-rejection test from requirements/.index.md.

Every REQ that declares a `route` and a non-`none` `auth_required` implies the same
test: the route rejects a request with no valid token. Written by hand, that scenario
is identical in every REQ and a change of status code touches every file. So it is not
written at all (W7 flags it if it is) — it is generated here, once, over every route.

    python tools/gen_auth_tests.py            # write OUT_PATH
    python tools/gen_auth_tests.py --check    # exit 1 if stale, write nothing (CI)

Run the lint first: this reads the index, and the index is produced by the lint.

ADAPT TO YOUR STACK: the three constants below are the only thing to change. Defaults
target Rust + rstest. For pytest, something like:

    OUT_PATH = "tests/test_auth_routes.py"
    CASE = '    ("{method}", "{path}"),  # {rid}'
    TEMPLATE = '''# {header}
# Covers: {covers}
import pytest

@pytest.mark.parametrize("method,path", [
{cases}
])
def protected_route_rejects_missing_auth(client, method, path):
    assert client.open(path, method=method).status_code == 401
'''
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX = REPO_ROOT / "requirements" / ".index.md"

# --- adapt from here ---------------------------------------------------------

AUTH_REQ = "REQ-AUTH-003"  # the REQ that specifies protected-route behavior
OUT_PATH = "tests/auth_routes.rs"
CASE = '#[case("{method}", "{path}")]  // {rid}'
TEMPLATE = '''// {header}
// Covers: {covers}

use rstest::rstest;

#[rstest]
{cases}
fn protected_route_rejects_missing_auth(#[case] method: &str, #[case] path: &str) {{
    let response = request_without_token(method, path);
    assert_eq!(response.status(), 401, "{{}} {{}} did not reject a missing token", method, path);
}}
'''

# --- to here -----------------------------------------------------------------

HEADER = "generated by tools/gen_auth_tests.py from requirements/.index.md — do not edit"


def rows() -> list[tuple[str, str, str]]:
    """Returns (method, path, req_id) for every protected route, sorted."""
    if not INDEX.exists():
        sys.exit(f"{INDEX} missing — run tools/lint_requirements.py first")
    out = []
    for line in INDEX.read_text(encoding="utf-8").splitlines():
        if line.startswith("<!--") or not line.strip():
            continue
        cols = [c.strip() for c in line.split("|")]
        if len(cols) < 5:
            continue
        rid, _module, _status, auth, route = cols[:5]
        if not rid.startswith("REQ-") or auth in ("none", "\u2014") or route == "\u2014":
            continue
        method, _, path = route.partition(" ")
        out.append((method, path, rid))
    return sorted(out, key=lambda r: (r[1], r[0]))


def render(protected: list[tuple[str, str, str]]) -> str:
    cases = "\n".join(
        CASE.format(method=m, path=p, rid=r) for m, p, r in protected
    )
    return TEMPLATE.format(header=HEADER, covers=AUTH_REQ, cases=cases)


def main(argv: list[str]) -> int:
    target = REPO_ROOT / OUT_PATH
    protected = rows()
    # No protected route yet -> the correct state of the repo is "no file at all",
    # so a fresh template ships with an empty tests/ and CI stays green.
    content = render(protected) if protected else None
    current = target.read_text(encoding="utf-8") if target.exists() else None

    if "--check" in argv:
        if current == content:
            print(f"{OUT_PATH}: up to date ({len(protected)} protected routes)")
            return 0
        if content is None:
            print(f"{OUT_PATH} exists but no REQ declares a protected route — "
                  f"run python tools/gen_auth_tests.py to remove it")
        else:
            print(f"{OUT_PATH} is stale — run python tools/gen_auth_tests.py and commit")
        return 1

    if content is None:
        if target.exists():
            target.unlink()
            print(f"removed {OUT_PATH}: no REQ declares a protected route")
        else:
            print(f"nothing to generate: no REQ declares a protected route")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(protected)} protected routes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
