#!/usr/bin/env python3
"""Lint for the files under requirements/.

Mechanically validates the methodology rules:
  E1  unparsable YAML block
  E2  heading and id field do not match
  E3  invalid id format (expected REQ-<PREFIX>-<number>)
  E4  duplicate id
  E5  status not allowed
  E6  priority not allowed
  E7  type not allowed
  E8  depends_on points to a non-existent id
  E9  status: tested but files.test empty
  E10 REQ module field differs from the file's module header
  E11 path in files.src/files.test does not exist in the repository
  E12 code (in modules' owner_dir) references a non-existent REQ
  E13 REQ heading at the wrong level (must be ### h3, nested under ## Requirements)
  E14 flow step references a non-existent REQ, or references nothing at all
  E15 a Covers: comment in a test dir names a non-existent REQ
  W1  unresolved pending_refs
  W2  file with REQs but no module header
  W3  deprecated REQ referenced in depends_on of an active REQ
  W4  REQ heading has no descriptive title (### REQ-ID - Title)
  W5  functional REQ not referenced by any flow (only if the module sets
      flow_coverage: required)
  W6  unresolved marker (???) in a draft flow — becomes E14 once approved
  W7  scenario duplicates a dependency's auth rejection (401/403 + a depends_on ID);
      remove it, coverage is implied by route + auth_required
  W8  auth_required set but no route declared
  W9  named scenario with no matching test (only for REQs past draft)

Exit code 1 on errors, 0 on warnings only or clean.
Files prefixed with "_" are ignored. 00_overview.md does not require a module header.

Every run rewrites requirements/.index.md (generated, committed, do not edit).
--emit-routes prints the route -> REQ table to stdout: a human-facing view,
never an artifact to commit.
--emit-testmap prints scenario -> REQ -> test rows to stdout: use it to go from a red
CI test back to the requirement it came from.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML missing: pip install pyyaml")

REPO_ROOT = Path(__file__).resolve().parent.parent
REQ_DIR = REPO_ROOT / "requirements"

ID_RE = re.compile(r"^REQ-[A-Z0-9]+-\d+$")
FLOW_ID_RE = re.compile(r"^FLOW-[A-Z0-9]+-[A-Z0-9]+(?:-[A-Z0-9]+)*$")
FLOW_HEADING_RE = re.compile(
    r"^(#{1,4})\s+(FLOW-[A-Z0-9]+-[A-Z0-9-]+)(?:\s*[-\u2013\u2014]\s*(.+?))?\s*$", re.MULTILINE
)
ANY_HEADING_RE = re.compile(r"^#{1,6}\s+\S", re.MULTILINE)
SECTION_RE = re.compile(r"^\*\*([A-Za-z ]+)\*\*\s*$", re.MULTILINE)
STEP_RE = re.compile(r"^\s*\d+\.\s+(.*\S)\s*$", re.MULTILINE)
BULLET_RE = re.compile(r"^\s*[-*]\s+(.*\S)\s*$", re.MULTILINE)
SCENARIO_RE = re.compile(r"^> \*\*Scenario[^\n]*(?:\n>[^\n]*)*", re.MULTILINE)
HTTP_DENY_RE = re.compile(r"\b(401|403)\b")
ROUTE_RE = re.compile(r"^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\s+/\S*$")
COVERS_RE = re.compile(r"Covers:\s*(REQ-[A-Z0-9]+-\d+)")
FN_NAME_RE = re.compile(r"(?:fn|def|function|void|public)\s+([A-Za-z_][A-Za-z0-9_]*)")
SCENARIO_NAME_RE = re.compile(r"^>\s*\*\*Scenario(?:\s+Outline)?:\s*([A-Za-z0-9_]+)\*\*", re.MULTILINE)
UNRESOLVED = "???"
INDEX_NAME = ".index.md"
INDEX_HEADER = (
    "<!-- generated by tools/lint_requirements.py \u2014 do not edit, do not hand-merge -->\n"
    "<!-- columns: id | module | status | auth | route | title | aliases | flows -->"
)
EMPTY_INDEX = INDEX_HEADER + "\n"
HEADING_RE = re.compile(r"^(#{1,4})\s+(REQ-[A-Z0-9]+-\d+)(?:\s*[-–—]\s*(.+?))?\s*$", re.MULTILINE)
FENCE_RE = re.compile(r"^```yaml\s*\n(.*?)^```\s*$", re.MULTILINE | re.DOTALL)
REQ_REF_RE = re.compile(r"REQ-[A-Z0-9]+-\d+")

REQ_HEADING_LEVEL = 3  # ### — nested under ## Requirements
FLOW_HEADING_LEVEL = 3  # ### — nested under ## Flows

STATUS_OK = {"draft", "approved", "implemented", "tested", "deprecated"}
PRIORITY_OK = {"low", "medium", "high"}
TYPE_OK = {"functional", "non_functional", "invariant"}

CODE_EXT = {
    ".rs", ".py", ".ts", ".tsx", ".js", ".jsx", ".go", ".java", ".kt",
    ".c", ".h", ".cpp", ".hpp", ".cs", ".rb", ".php", ".swift", ".sql", ".sh",
}


def line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def sections_of(body: str, offset: int = 0) -> dict[str, tuple[str, int]]:
    """Splits a **Label** delimited body into {label: (text, absolute_offset)}."""
    marks = list(SECTION_RE.finditer(body))
    out: dict[str, tuple[str, int]] = {}
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(body)
        out[m.group(1).strip().lower()] = (body[m.end():end], offset + m.end())
    return out


def parse_file(path: Path, problems: list) -> tuple[dict | None, list[dict], list[dict]]:
    """Returns (module_header, [req], [flow]) for a .md file."""
    text = path.read_text(encoding="utf-8")
    headings = [
        (m.start(), len(m.group(1)), m.group(2), (m.group(3) or "").strip())
        for m in HEADING_RE.finditer(text)
    ]
    flow_headings = [
        (m.start(), len(m.group(1)), m.group(2), (m.group(3) or "").strip())
        for m in FLOW_HEADING_RE.finditer(text)
    ]
    heading_starts = [m.start() for m in ANY_HEADING_RE.finditer(text)]
    module_header = None
    reqs: list[dict] = []
    flows: list[dict] = []

    for m in FENCE_RE.finditer(text):
        line = line_of(text, m.start())
        loc = f"{path.name}:{line}"
        try:
            data = yaml.safe_load(m.group(1))
        except yaml.YAMLError as e:
            problems.append(("E1", loc, f"unparsable YAML: {e}"))
            continue
        if not isinstance(data, dict):
            continue

        rid = str(data.get("id", ""))

        if rid.startswith("FLOW-"):
            prev = [h for h in flow_headings if h[0] < m.start()]
            _, h_level, h_id, h_title = prev[-1] if prev else (0, None, None, None)
            nxt = [s for s in heading_starts if s > m.end()]
            body = text[m.end():nxt[0] if nxt else len(text)]
            flows.append({
                "data": data, "loc": loc, "path": path,
                "heading_id": h_id, "heading_level": h_level, "heading_title": h_title,
                "body": body, "body_offset": m.end(), "text": text,
            })
        elif "id" in data:
            # REQ heading immediately preceding the block
            prev = [h for h in headings if h[0] < m.start()]
            if prev:
                _, heading_level, heading_id, heading_title = prev[-1]
            else:
                heading_level = heading_id = heading_title = None
            nxt = [s for s in heading_starts if s > m.end()]
            body = text[m.end():nxt[0] if nxt else len(text)]
            reqs.append({
                "data": data, "loc": loc, "body": body,
                "heading_id": heading_id, "heading_level": heading_level, "heading_title": heading_title,
            })
        elif "module" in data and module_header is None:
            module_header = {"data": data, "loc": loc}

    return module_header, reqs, flows


def main(argv: list[str]) -> int:
    emit_routes = "--emit-routes" in argv
    emit_testmap = "--emit-testmap" in argv
    problems: list[tuple[str, str, str]] = []  # (code, location, message)
    all_reqs: dict[str, dict] = {}  # id -> {status, loc, depends_on, ...}
    all_flows: dict[str, dict] = {}
    flow_refs: dict[str, dict[str, str]] = {}  # flow id -> {REQ id: source location}
    coverage_modules: set[str] = set()
    owner_dirs: set[str] = set()
    test_dirs: set[str] = set()

    files = sorted(
        p for p in REQ_DIR.glob("*.md")
        if not p.name.startswith("_") and p.name != INDEX_NAME
    )
    if not files:
        REQ_DIR.mkdir(parents=True, exist_ok=True)
        (REQ_DIR / INDEX_NAME).write_text(EMPTY_INDEX, encoding="utf-8")
        print(f"No files in {REQ_DIR} — wrote an empty requirements/{INDEX_NAME}")
        return 0

    # Pass 1: parsing and local validations
    for path in files:
        module_header, reqs, flows = parse_file(path, problems)

        if reqs and module_header is None and not path.name.startswith("00_"):
            problems.append(("W2", path.name, "file with REQs but no module header"))

        header_data = (module_header or {}).get("data", {})
        file_module = header_data.get("module")
        if header_data.get("owner_dir"):
            owner_dirs.add(str(header_data["owner_dir"]))
        for td in header_data.get("test_dirs") or []:
            test_dirs.add(str(td))
        if str(header_data.get("flow_coverage", "optional")) == "required" and file_module:
            coverage_modules.add(str(file_module))

        for fl in flows:
            d, loc = fl["data"], fl["loc"]
            fid = str(d.get("id", ""))
            if not FLOW_ID_RE.match(fid):
                problems.append(("E3", loc, f"flow id '{fid}' does not match FLOW-<MODULE>-<NAME>"))
                continue
            if fl["heading_id"] != fid:
                problems.append(("E2", loc, f"flow heading '{fl['heading_id']}' \u2260 id '{fid}'"))
            if fl["heading_level"] and fl["heading_level"] != FLOW_HEADING_LEVEL:
                problems.append(("E14", loc, f"{fid}: heading is h{fl['heading_level']}, expected h{FLOW_HEADING_LEVEL} (###)"))
            if fid in all_flows:
                problems.append(("E4", loc, f"duplicate flow id '{fid}'"))
                continue
            if d.get("status") not in STATUS_OK:
                problems.append(("E5", loc, f"{fid}: status '{d.get('status')}' not in {sorted(STATUS_OK)}"))
            if file_module and d.get("module") != file_module:
                problems.append(("E10", loc, f"{fid}: module '{d.get('module')}' \u2260 file header '{file_module}'"))

            draft = d.get("status") == "draft"
            secs = sections_of(fl["body"], fl["body_offset"])

            def at(off: int) -> str:
                return f"{path.name}:{line_of(fl['text'], off)}"

            sec_steps, steps_off = secs.get("steps", ("", 0))
            sec_notes, notes_off = secs.get("notes", ("", 0))

            steps = list(STEP_RE.finditer(sec_steps))
            if not steps:
                problems.append(("E14", loc, f"{fid}: no numbered steps under **Steps**"))
            for n, m2 in enumerate(steps, 1):
                step = m2.group(1)
                sloc = at(steps_off + m2.start())
                refs = REQ_REF_RE.findall(step)
                if UNRESOLVED in step and not refs:
                    problems.append(("W6" if draft else "E14", sloc,
                                     f"{fid} step {n}: unresolved reference ({UNRESOLVED})"))
                elif not refs:
                    problems.append(("E14", sloc, f"{fid} step {n}: no REQ reference"))
                for ref in refs:
                    flow_refs.setdefault(fid, {})[ref] = sloc
            for m2 in BULLET_RE.finditer(sec_notes):
                note = m2.group(1)
                nloc = at(notes_off + m2.start())
                if UNRESOLVED in note:
                    problems.append(("W6" if draft else "E14", nloc,
                                     f"{fid} note: unresolved reference ({UNRESOLVED})"))
                for ref in REQ_REF_RE.findall(note):
                    flow_refs.setdefault(fid, {})[ref] = nloc

            all_flows[fid] = {"loc": loc, "module": d.get("module"), "status": d.get("status")}

        for r in reqs:
            d, loc = r["data"], r["loc"]
            rid = str(d.get("id", ""))

            if not ID_RE.match(rid):
                problems.append(("E3", loc, f"id '{rid}' does not match REQ-<PREFIX>-<number>"))
                continue
            if r["heading_id"] != rid:
                problems.append(("E2", loc, f"heading '{r['heading_id']}' ≠ id '{rid}'"))
            if r["heading_level"] is not None and r["heading_level"] != REQ_HEADING_LEVEL:
                problems.append(("E13", loc, f"{rid}: heading is h{r['heading_level']}, expected h{REQ_HEADING_LEVEL} (###)"))
            if not r["heading_title"]:
                problems.append(("W4", loc, f"{rid}: heading has no descriptive title (### {rid} - Title)"))
            if rid in all_reqs:
                problems.append(("E4", loc, f"duplicate id '{rid}' (already in {all_reqs[rid]['loc']})"))
                continue

            status = d.get("status")
            if status not in STATUS_OK:
                problems.append(("E5", loc, f"{rid}: status '{status}' not in {sorted(STATUS_OK)}"))
            if "priority" in d and d["priority"] not in PRIORITY_OK:
                problems.append(("E6", loc, f"{rid}: priority '{d['priority']}' not in {sorted(PRIORITY_OK)}"))
            if "type" in d and d["type"] not in TYPE_OK:
                problems.append(("E7", loc, f"{rid}: type '{d['type']}' not in {sorted(TYPE_OK)}"))

            if status == "tested":
                tests = (d.get("files") or {}).get("test") or []
                if not tests:
                    problems.append(("E9", loc, f"{rid}: status tested but files.test empty"))

            for kind in ("src", "test"):
                for entry in (d.get("files") or {}).get(kind) or []:
                    rel = str(entry).split("::")[0]  # tests/x.rs::function -> tests/x.rs
                    if not (REPO_ROOT / rel).exists():
                        problems.append(("E11", loc, f"{rid}: files.{kind} '{rel}' does not exist"))

            if file_module and d.get("module") != file_module:
                problems.append(("E10", loc, f"{rid}: module '{d.get('module')}' ≠ file header '{file_module}'"))

            pending = d.get("pending_refs") or []
            if pending:
                problems.append(("W1", loc, f"{rid}: {len(pending)} pending_refs to resolve"))

            deps = d.get("depends_on") or []
            auth = d.get("auth_required", "none")
            route = d.get("route")
            if route is not None and not ROUTE_RE.match(str(route).strip()):
                problems.append(("E7", loc, f"{rid}: route '{route}' is not '<METHOD> /path'"))
            if auth not in (None, "none") and not route:
                problems.append(("W8", loc, f"{rid}: auth_required '{auth}' but no route declared"))

            for sc in SCENARIO_RE.findall(r["body"]):
                if HTTP_DENY_RE.search(sc) and any(dep in sc for dep in deps):
                    problems.append(("W7", loc, f"{rid}: scenario duplicates a dependency's auth rejection \u2014 remove, implied by route + auth_required"))
                    break

            all_reqs[rid] = {
                "scenarios": SCENARIO_NAME_RE.findall(r["body"]),
                "tests": (d.get("files") or {}).get("test") or [],
                "status": status,
                "loc": loc,
                "depends_on": deps,
                "module": d.get("module") or file_module,
                "auth": auth,
                "route": str(route).strip() if route else None,
                "title": r["heading_title"] or "",
                "aliases": d.get("aliases") or [],
                "type": d.get("type"),
            }

    # Pass 2a: flow -> REQ references, and reverse index
    covered_by: dict[str, list[str]] = {}
    for fid, refs in flow_refs.items():
        for ref, rloc in sorted(refs.items()):
            if ref not in all_reqs:
                problems.append(("E14", rloc, f"{fid}: references unknown requirement '{ref}'"))
            else:
                covered_by.setdefault(ref, []).append(fid)

    # W5: functional REQ not in any flow, only for opt-in modules
    for rid, info in all_reqs.items():
        if (info["type"] == "functional" and info["module"] in coverage_modules
                and info["status"] != "deprecated" and rid not in covered_by):
            problems.append(("W5", info["loc"], f"{rid}: functional REQ not referenced by any flow"))

    # Pass 2: cross references
    for rid, info in all_reqs.items():
        for dep in info["depends_on"]:
            if dep not in all_reqs:
                problems.append(("E8", info["loc"], f"{rid}: depends_on '{dep}' does not exist"))
            elif all_reqs[dep]["status"] == "deprecated" and info["status"] != "deprecated":
                problems.append(("W3", info["loc"], f"{rid}: depends on '{dep}' which is deprecated"))

    # Pass 3: REQ references inside module code (owner_dir)
    seen_code_refs: set[tuple[str, str]] = set()
    for od in sorted(owner_dirs):
        base = REPO_ROOT / od
        if not base.exists():
            continue
        for f in base.rglob("*"):
            if not (f.is_file() and f.suffix in CODE_EXT):
                continue
            try:
                content = f.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            rel_f = str(f.relative_to(REPO_ROOT))
            for m in REQ_REF_RE.finditer(content):
                ref = m.group(0)
                if ref not in all_reqs and (rel_f, ref) not in seen_code_refs:
                    seen_code_refs.add((rel_f, ref))
                    problems.append(("E12", f"{rel_f}:{line_of(content, m.start())}",
                                     f"code references unknown requirement '{ref}'"))

    # Generated index — rewritten on every run
    lines = INDEX_HEADER.split("\n")
    for rid in sorted(all_reqs):
        i = all_reqs[rid]
        lines.append(" | ".join([
            rid,
            str(i["module"] or "\u2014"),
            str(i["status"] or "\u2014"),
            str(i["auth"] or "none"),
            i["route"] or "\u2014",
            i["title"] or "\u2014",
            ",".join(str(a) for a in i["aliases"]) or "\u2014",
            ",".join(sorted(covered_by.get(rid, []))) or "\u2014",
        ]))
    for fid in sorted(all_flows):
        f = all_flows[fid]
        lines.append(" | ".join([
            fid, str(f["module"] or "\u2014"), str(f["status"] or "\u2014"),
            "\u2014", "\u2014", "\u2014", "\u2014",
            ",".join(sorted(flow_refs.get(fid, {}))) or "\u2014",
        ]))
    (REQ_DIR / INDEX_NAME).write_text("\n".join(lines) + "\n", encoding="utf-8")

    if emit_routes:
        rows = sorted(
            (i["route"], rid, i) for rid, i in all_reqs.items() if i["route"]
        )
        print("| Method | Path | REQ | Auth | Module |")
        print("|---|---|---|---|---|")
        for route, rid, i in rows:
            method, _, path_ = route.partition(" ")
            print(f"| {method} | {path_} | {rid} | {i['auth']} | {i['module']} |")
        print()

    # Pass 4: Covers: comments inside declared test dirs
    covers: dict[str, list[str]] = {}  # REQ id -> ["path::function", ...]
    for td in sorted(test_dirs):
        base = REPO_ROOT / td
        if not base.exists():
            continue
        for f in sorted(base.rglob("*")):
            if not (f.is_file() and f.suffix in CODE_EXT):
                continue
            try:
                content = f.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            rel_f = str(f.relative_to(REPO_ROOT))
            for m in COVERS_RE.finditer(content):
                ref = m.group(1)
                ln = line_of(content, m.start())
                if ref not in all_reqs:
                    problems.append(("E15", f"{rel_f}:{ln}",
                                     f"Covers: names unknown requirement '{ref}'"))
                    continue
                tail = content[m.end():]
                fn = FN_NAME_RE.search(tail)
                covers.setdefault(ref, []).append(f"{rel_f}::{fn.group(1) if fn else '?'}")

    # W9: named scenario with no matching test, once the REQ is past draft
    testmap: list[tuple[str, str, str]] = []  # (scenario, REQ, location)
    for rid, i in sorted(all_reqs.items()):
        found = covers.get(rid, [])
        declared = [str(x) for x in i["tests"]]
        for sc in i["scenarios"]:
            hit = next((c for c in found if c.endswith(f"::{sc}")), None) \
                or next((d for d in declared if d.endswith(f"::{sc}")), None)
            testmap.append((sc, rid, hit or "\u2014"))
            if hit is None and i["status"] not in ("draft", "deprecated"):
                problems.append(("W9", i["loc"], f"{rid}: scenario '{sc}' has no matching test"))

    if emit_testmap:
        print("| Scenario | REQ | Test |")
        print("|---|---|---|")
        for sc, rid, loc2 in testmap:
            print(f"| {sc} | {rid} | {loc2} |")
        print()

    # Report
    errors = [p for p in problems if p[0].startswith("E")]
    warnings = [p for p in problems if p[0].startswith("W")]

    for code, loc, msg in sorted(problems, key=lambda p: (p[0][0] != "E", p[1])):
        kind = "ERROR" if code.startswith("E") else "WARN "
        print(f"{kind} [{code}] {loc}  {msg}")

    print(
        f"\n{len(files)} files, {len(all_reqs)} requirements, {len(all_flows)} flows — "
        f"{len(errors)} errors, {len(warnings)} warnings\n"
        f"wrote requirements/{INDEX_NAME}"
    )
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
